version: "3.7"

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:14.0
    restart: always
    ports:
      - "5454:5432"
    environment:
      POSTGRES_USER: web
      POSTGRES_PASSWORD: web
      POSTGRES_DB: web